services:
  - type: web
    name: pickledgerpro
    runtime: docker
    dockerfilePath: ./Dockerfile
    plan: free
    envVars:
      - key: PORT
        value: 8765
      - key: ENABLE_SPORTYTRADER_REMOTE
        value: "true"
      - key: FIREBASE_PROJECT_ID
        sync: false
      - key: FIREBASE_PRIVATE_KEY
        sync: false
      - key: FIREBASE_CLIENT_EMAIL
        sync: false
      - key: FIREBASE_PRIVATE_KEY_ID
        sync: false
      - key: FIREBASE_CLIENT_ID
        sync: false
      - key: ADMIN_PICKS_SECRET
        value: 611e61c79074c0845929e581ebd484b527ecadb483dd431259de0793e47459e7
    healthCheckPath: /health
