import json
from pathlib import Path


ROOT = Path(__file__).resolve().parents[2]


def test_today_is_a_read_only_cross_app_dashboard():
    html = (ROOT / "today" / "index.html").read_text(encoding="utf-8")
    script = (ROOT / "src" / "today" / "main.ts").read_text(encoding="utf-8")
    data = (ROOT / "src" / "today" / "data.ts").read_text(encoding="utf-8")

    assert 'href="https://harsh.bet/today/"' in html
    assert 'id="priority-card"' in html
    assert 'id="advice-card"' in html
    assert 'id="schedule-card"' in html
    assert 'id="habits-card"' in html
    assert 'id="nutrition-card"' in html
    assert 'id="workout-card"' in html
    assert 'id="trend-card"' in html
    assert "Daymark" in script
    assert "Slate" in script
    assert "Fare" in script
    assert "Gym" in script
    assert "put(" not in data
    assert "deleteDatabase" not in data
    assert "request.transaction?.abort()" in data
    for theme in ("light", "system", "dark"):
        assert f'data-theme-option="{theme}"' in html


def test_today_advice_is_explainable_and_derived_without_writes():
    derive = (ROOT / "src" / "today" / "derive.ts").read_text(encoding="utf-8")
    script = (ROOT / "src" / "today" / "main.ts").read_text(encoding="utf-8")

    assert "derivePressure" in derive
    assert "deriveAdvice" in derive
    assert "trendDelta" in derive
    assert "Why this recommendation" in script
    assert "Pressure describes remaining load, not performance." in script


def test_today_does_not_model_slates_retired_schedule_blocks():
    """Slate dropped schedule blocks, so nothing here may count or display them.

    Reading `blocks` cost Today its whole Slate integration once already: the
    validator required an array Slate never writes, so both Slate-backed cards
    showed "not connected" on every device.
    """
    types = (ROOT / "src" / "today" / "types.ts").read_text(encoding="utf-8")
    derive = (ROOT / "src" / "today" / "derive.ts").read_text(encoding="utf-8")
    data = (ROOT / "src" / "today" / "data.ts").read_text(encoding="utf-8")

    assert "SlateBlock" not in types
    assert "SlateBlock" not in derive
    assert "state?.blocks" not in derive
    assert "raw.blocks" not in data
    assert "Array.isArray(raw.tasks) && Array.isArray(raw.sections)" in data
    assert "raw.version === 1" in data


def test_today_validator_is_covered_by_a_real_slate_payload():
    fixture = ROOT / "tests" / "fixtures" / "slate-persisted-payload.json"
    payload = json.loads(fixture.read_text(encoding="utf-8"))
    unit_test = (ROOT / "src" / "today" / "data.test.ts").read_text(encoding="utf-8")

    # Generated by Slate's own buildStorageEnvelope, so the nesting is real.
    assert payload["storageFormat"] == "slate-v1"
    assert "tasks" not in payload
    assert "blocks" not in payload["state"]
    assert payload["state"]["version"] == 1
    assert payload["state"]["tasks"]
    assert "validSlate" in unit_test
    assert fixture.name in unit_test


def test_today_uses_each_apps_existing_storage_contract():
    data = (ROOT / "src" / "today" / "data.ts").read_text(encoding="utf-8")
    for contract in (
        "daymark-tracker-state-v2",
        "slate-todo-state-v1",
        "fare-state-v1",
        "harsh-gym-program-v1",
        "harsh-gym-logs-v1",
    ):
        assert contract in data


def test_today_is_in_the_multipage_build():
    config = (ROOT / "vite.config.ts").read_text(encoding="utf-8")
    assert "today: 'today/index.html'" in config
